//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoProcessosCameraMunicipal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Especialista
    {
        public int TipoProjetoId { get; set; }
        public int FuncionarioNumero1 { get; set; }
    
        public virtual Funcionario Funcionario { get; set; }
        public virtual TipoProjeto TipoProjeto { get; set; }
    }
}
