//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoProcessosCameraMunicipal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projeto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projeto()
        {
            this.Documento = new HashSet<Documento>();
            this.Parecer = new HashSet<Parecer>();
            this.ProjetoAtribuido = new HashSet<ProjetoAtribuido>();
        }
    
        public int Id { get; set; }
        public string EstadoProjeto { get; set; }
        public System.DateTime DataEntrada { get; set; }
        public System.DateTime DataAprovacao { get; set; }
        public int TipoProjetoId { get; set; }
        public int ProcessoId { get; set; }
    
        public virtual TipoProjeto TipoProjeto { get; set; }
        public virtual Processo Processo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documento> Documento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parecer> Parecer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjetoAtribuido> ProjetoAtribuido { get; set; }
    }
}
