//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoCamaraMunicipal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestaoCamaraMunicipalContainer : DbContext
    {
        public GestaoCamaraMunicipalContainer()
            : base("name=GestaoCamaraMunicipalContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TipoDocumento> TipoDocumentoSet { get; set; }
        public virtual DbSet<Promotor> PromotorSet { get; set; }
        public virtual DbSet<Processo> ProcessoSet { get; set; }
        public virtual DbSet<EstadoProcesso> EstadoProcessoSet { get; set; }
        public virtual DbSet<Documento> DocumentoSet { get; set; }
        public virtual DbSet<Projeto> ProjetoSet { get; set; }
        public virtual DbSet<TipoProjeto> TipoProjetoSet { get; set; }
        public virtual DbSet<Parecer> ParecerSet { get; set; }
        public virtual DbSet<Funcionario> FuncionarioSet { get; set; }
        public virtual DbSet<Especialista> EspecialistaSet { get; set; }
        public virtual DbSet<ProjetoAtribuido> ProjetoAtribuidoSet { get; set; }
    }
}
