//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoCamaraMunicipal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Promotor()
        {
            this.Processo = new HashSet<Processo>();
        }

        public Promotor(int nIF, string nome, string morada, string telemovel, string email, string codigoAcesso, string senha)
        {
            NIF = nIF;
            Nome = nome;
            Morada = morada;
            Telemovel = telemovel;
            Email = email;
            CodigoAcesso = codigoAcesso;
            Senha = senha;
        }

        public int NIF { get; set; }
        public string Nome { get; set; }
        public string Morada { get; set; }
        public string Telemovel { get; set; }
        public string Email { get; set; }
        public string CodigoAcesso { get; set; }
        public string Senha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Processo> Processo { get; set; }
        public override string ToString()
        {
            return Nome + "(" + NIF + ")";
        }
    }

}
